/**
 * Auto Quiz Generation Service
 * Calls Assessment Agent to generate quiz when user completes a course
 */

import axios from 'axios';
import pool from '../config/db.js';
import { RowDataPacket } from 'mysql2';
import { AutoGeneratedQuizModel, GeneratedQuestion } from '../models/AutoGeneratedQuiz.js';
import logger from './logger.js';

const ASSESSMENT_AGENT_URL = 'http://lyw-assessment:8008';

interface CourseContentData {
    title: string;
    title_vi: string;
    description: string;
    concepts: string[];
    lessons: { title: string; content: string }[];
}

export const AutoQuizService = {
    /**
     * Get course content for quiz generation
     */
    async getCourseContent(courseId: number): Promise<CourseContentData | null> {
        try {
            // Get course info
            const [courses] = await pool.query<RowDataPacket[]>(
                `SELECT id, title_en, title_vi, description_en, description_vi 
         FROM courses WHERE id = ?`,
                [courseId]
            );

            if (courses.length === 0) return null;
            const course = courses[0];

            // Get all lessons with content
            const [lessons] = await pool.query<RowDataPacket[]>(
                `SELECT title_en, title_vi, content_en, content_vi 
         FROM lessons WHERE course_id = ? ORDER BY order_index`,
                [courseId]
            );

            // Extract concepts from lesson titles and content
            const concepts: string[] = [];
            const lessonData: { title: string; content: string }[] = [];

            for (const lesson of lessons) {
                concepts.push(lesson.title_en || lesson.title_vi);
                lessonData.push({
                    title: lesson.title_en || lesson.title_vi,
                    content: (lesson.content_en || lesson.content_vi || '').substring(0, 1000),
                });
            }

            return {
                title: course.title_en || course.title_vi,
                title_vi: course.title_vi || course.title_en,
                description: course.description_en || course.description_vi || '',
                concepts,
                lessons: lessonData,
            };
        } catch (error) {
            logger.error('Failed to get course content:', error);
            return null;
        }
    },

    /**
     * Call Assessment Agent to generate questions
     */
    async callAssessmentAgent(courseContent: CourseContentData): Promise<GeneratedQuestion[]> {
        try {
            // Build concept string from course content
            const conceptStr = courseContent.concepts.join(', ');

            // Try calling Assessment Agent with Bloom's Taxonomy endpoint
            const response = await axios.post(
                `${ASSESSMENT_AGENT_URL}/generate-by-blooms`,
                {
                    concept: conceptStr,
                    course_title: courseContent.title,
                    bloom_level: 'understand', // Start with understanding level
                    num_questions: 10,
                    difficulty: 'medium',
                    include_explanation: true,
                },
                { timeout: 60000 } // 60 second timeout
            );

            if (response.data?.success && response.data?.questions) {
                return response.data.questions.map((q: any) => ({
                    question: q.question || q.text,
                    type: q.type || 'multiple_choice',
                    options: q.options || q.choices || [],
                    correct_answer: q.correct_answer ?? q.answer ?? 0,
                    explanation: q.explanation || '',
                    difficulty: q.difficulty || 'medium',
                    bloom_level: q.bloom_level || 'understand',
                }));
            }

            // Fallback: Try basic generate endpoint
            const fallbackResponse = await axios.post(
                `${ASSESSMENT_AGENT_URL}/generate`,
                {
                    concept: conceptStr,
                    num_questions: 10,
                    question_types: ['multiple_choice', 'true_false'],
                },
                { timeout: 60000 }
            );

            if (fallbackResponse.data?.questions) {
                return fallbackResponse.data.questions;
            }

            throw new Error('No questions returned from Assessment Agent');
        } catch (error: any) {
            logger.error('Assessment Agent call failed:', error.message);
            // Return fallback questions if agent is not available
            return this.generateFallbackQuestions(courseContent);
        }
    },

    /**
     * Generate fallback questions if Assessment Agent is unavailable
     */
    generateFallbackQuestions(courseContent: CourseContentData): GeneratedQuestion[] {
        const questions: GeneratedQuestion[] = [];

        // Generate basic questions from course concepts
        courseContent.concepts.slice(0, 5).forEach((concept, index) => {
            questions.push({
                question: `What is the main concept of "${concept}"?`,
                type: 'multiple_choice',
                options: [
                    `Understanding ${concept} fundamentals`,
                    `Advanced ${concept} techniques`,
                    `${concept} best practices`,
                    `All of the above`,
                ],
                correct_answer: 3, // "All of the above"
                explanation: `This question tests your understanding of ${concept}.`,
                difficulty: 'medium',
                bloom_level: 'understand',
            });
        });

        // Add some true/false questions
        courseContent.concepts.slice(0, 3).forEach((concept) => {
            questions.push({
                question: `True or False: ${concept} is an important topic covered in this course.`,
                type: 'true_false',
                options: ['True', 'False'],
                correct_answer: 0, // True
                explanation: `${concept} was covered as part of the course curriculum.`,
                difficulty: 'easy',
                bloom_level: 'remember',
            });
        });

        return questions;
    },

    /**
     * Generate and save quiz for user when course is completed
     */
    async generateQuizForCompletion(userId: number, courseId: number): Promise<number | null> {
        try {
            // Check if quiz already exists for this user and course
            const exists = await AutoGeneratedQuizModel.existsForUserCourse(userId, courseId);
            if (exists) {
                logger.info(`Auto quiz already exists for user ${userId}, course ${courseId}`);
                return null;
            }

            // Get course content
            const courseContent = await this.getCourseContent(courseId);
            if (!courseContent) {
                logger.error(`Course content not found for course ${courseId}`);
                return null;
            }

            logger.info(`Generating auto quiz for user ${userId}, course: ${courseContent.title}`);

            // Call Assessment Agent to generate questions
            const questions = await this.callAssessmentAgent(courseContent);

            if (!questions || questions.length === 0) {
                logger.error('No questions generated');
                return null;
            }

            // Save quiz to database
            const quizId = await AutoGeneratedQuizModel.create({
                user_id: userId,
                course_id: courseId,
                title: `Bài tập tổng kết: ${courseContent.title_vi || courseContent.title}`,
                description: `Bài tập tự động được tạo bởi AI sau khi bạn hoàn thành khóa học "${courseContent.title_vi || courseContent.title}". Hãy làm bài để củng cố kiến thức!`,
                passing_score: 70,
                time_limit: 30,
                questions,
            });

            logger.info(`Auto quiz created with ID ${quizId} for user ${userId}, course ${courseId}`);

            // Create notification for user
            await this.notifyUser(userId, courseId, quizId, courseContent.title_vi || courseContent.title);

            return quizId;
        } catch (error) {
            logger.error('Failed to generate auto quiz:', error);
            return null;
        }
    },

    /**
     * Create notification for user about new quiz
     */
    async notifyUser(userId: number, courseId: number, quizId: number, courseTitle: string): Promise<void> {
        try {
            await pool.query(
                `INSERT INTO notifications (user_id, title, message, type, link, is_read)
         VALUES (?, ?, ?, 'quiz', ?, 0)`,
                [
                    userId,
                    '🎉 Bài tập tổng kết đã sẵn sàng!',
                    `Chúc mừng bạn đã hoàn thành khóa học "${courseTitle}"! AI đã tạo một bài tập tổng kết để giúp bạn củng cố kiến thức. Hãy làm bài ngay!`,
                    `/auto-quiz/${quizId}`,
                ]
            );
        } catch (error) {
            logger.error('Failed to create notification:', error);
        }
    },
};

export default AutoQuizService;
